//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesinhPalmy_vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string NickSkype { get; set; }
        public string NickYahoo { get; set; }
        public int Ord { get; set; }
        public string Target { get; set; }
        public string Hotline { get; set; }
        public int IdGroupSupport { get; set; }
        public int Position { get; set; }
        public bool Active { get; set; }
    
        public virtual GroupSupport GroupSupport { get; set; }
    }
}
