//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesinhPalmy_vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Support_NameGroup
    {
        public string groupName { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string Nick { get; set; }
        public string Type { get; set; }
        public int Image { get; set; }
        public string Target { get; set; }
        public string Ord { get; set; }
        public int Tel { get; set; }
        public int IdGroupSupport { get; set; }
        public bool Position { get; set; }
    }
}
